Fix HostVarsVars object' has no attribute 'role
`hostvars` might have added new other same level attributes and because
this template loops on all available attributes, we cannot expect
'role' would be present in those new ones as well.

This changes checks if 'role' is present before carry on, otherwise
we would get this nice traceback:

Traceback (most recent call last):
  File "/home/mario/tpa/tpa-venv/lib/python3.12/site-packages/ansible/plugins/action/template.py", line 152, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False, overrides=overrides)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/tpa/tpa-venv/lib/python3.12/site-packages/ansible/template/__init__.py", line 1015, in do_template
    raise AnsibleUndefinedVariable(e, orig_exc=e)
ansible.errors.AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'role'. 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'role'
fatal: [pemserver]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'role'. 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'role'"