Apply patches/RM16946.diff during tpaexec setup
The patch, extracted (with some changes) from a long-pending upstream PR
https://github.com/boto/boto/pull/3699, solves a problem with using Boto
through an https_proxy:

    TypeError: a bytes-like object is required, not 'str'

Since we certainly don't want to maintain a Boto fork, applying the
patch is the best alternative available, even though it's not very
satisfying.

Reported by Marc F.

References: RM16946