Reject empty lines in --hostnames-from input file
The default `[…]*` pattern inadvertently matched empty lines, so if you
used a hostnames.txt file that contained empty lines, we would try to
use that as a hostname, and fail like this:

tpaexec configure B24DC1  --architecture BDR-Simple --num-instances 3 --platform bare --postgres-version 11 --bdr-version 3 --hostnames-from hostnames.txt
Traceback (most recent call last):
  File "/Users/oliverriggs/sources/ansible/lib/ansible/template/__init__.py", line 804, in do_template
    res = j2_concat(rf)
  File "<template>", line 20, in root
  File "/Users/oliverriggs/sources/tpaexec/tpa-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: list object has no element 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oliverriggs/sources/tpaexec/architectures/BDR-Simple/configure", line 111, in <module>
    BDR_Simple().configure()
  File "/Users/oliverriggs/sources/tpaexec/architectures/lib/tpaexec/architecture.py", line 32, in configure
    self.process_arguments(self.args)
  File "/Users/oliverriggs/sources/tpaexec/architectures/lib/tpaexec/architecture.py", line 268, in process_arguments
    self.load_topology(args)
  File "/Users/oliverriggs/sources/tpaexec/architectures/lib/tpaexec/architecture.py", line 363, in load_topology
    y = self.load_yaml('main.yml.j2', args)
  File "/Users/oliverriggs/sources/tpaexec/architectures/lib/tpaexec/architecture.py", line 613, in load_yaml
    text = self.expand_template(filename, vars, loader)
  File "/Users/oliverriggs/sources/tpaexec/architectures/lib/tpaexec/architecture.py", line 621, in expand_template
    return templar.do_template(template)
  File "/Users/oliverriggs/sources/ansible/lib/ansible/template/__init__.py", line 838, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: list object has no element 2

The new pattern rejects empty lines, and you get an error about not
having supplied the required number of hostnames instead.

References: RM70309