Validate etcd roles when deploying BDR4 clusters
When using BDR 4 with HARP and `harp_consensus_protocol: etcd`, at
least one instance must have the `etcd` role defined in config.yml.
Typically, the `etcd` role is added to BDR primary instances. TPA will
validate this requirement during provision and fail with a clear error
message if no etcd roles are found.

Despite this is rare to happen because the configure step will add this
role, when editing the file manually for any reason, some mistakes could
be made, resulting in obscure and expensive errors to debug like:

harpctl get cluster
Error: "Cluster state has not been established"

references: TPA-933