Avoid using 'conf' as a variable name too
This led to errors like the following:

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ams/2q-ansible/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/home/ams/2q-ansible/lib/ansible/executor/task_executor.py", line 488, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/ams/2q-ansible/lib/ansible/plugins/action/template.py", line 86, in run
    dest = self._remote_expand_user(dest)
  File "/home/ams/2q-ansible/lib/ansible/plugins/action/__init__.py", line 481, in _remote_expand_user
    if not path.startswith('~'):  # FIXME: Windows paths may start with "~ instead of just ~
AttributeError: 'dict' object has no attribute 'startswith'

Where "path" == the template 'dest' that we specify, and it should be a
string, definitely not a dict.