Remove jinja2.ext.with_ from ansible.cfg
(a) We don't actually use it anywhere (any more)
(b) It's builtin to jinja2 as of 3.1, so people who `tpaexec setup` and
    get 3.1 with get an error:

    Warning: :  * Failed to parse /opt/EDB/TPA/ansible/hosts with yaml plugin:
    module 'jinja2.ext' has no attribute 'with_'

Reported by Amruta.