Require barman-cli 2.9 on RH distributions
With v2.10, the barman-cli RPM has grown an unfortunate and ill-advised
dependency on python-boto3 (which is not required to use barman-cli in
toto, only the new s3 backup stuff).

Worse still, because of this new dependency, the package just doesn't
install on RHEL7:

[root@kingpin ~]# yum install barman-cli
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package barman-cli.noarch 0:2.10-2.el7 will be installed
--> Processing Dependency: python-barman = 2.10 for package: barman-cli-2.10-2.el7.noarch
--> Processing Dependency: python-boto3 for package: barman-cli-2.10-2.el7.noarch
--> Running transaction check
---> Package barman-cli.noarch 0:2.10-2.el7 will be installed
--> Processing Dependency: python-boto3 for package: barman-cli-2.10-2.el7.noarch
---> Package python-barman.noarch 0:2.10-2.el7 will be installed
--> Processing Dependency: python-argh >= 0.21.2 for package: python-barman-2.10-2.el7.noarch
--> Processing Dependency: python-psycopg2 >= 2.4.2 for package: python-barman-2.10-2.el7.noarch
--> Processing Dependency: python-argcomplete for package: python-barman-2.10-2.el7.noarch
--> Running transaction check
---> Package barman-cli.noarch 0:2.10-2.el7 will be installed
--> Processing Dependency: python-boto3 for package: barman-cli-2.10-2.el7.noarch
---> Package python2-argcomplete.noarch 0:1.7.0-4.el7 will be installed
---> Package python2-argh.noarch 0:0.26.1-6.el7 will be installed
---> Package python2-psycopg2.x86_64 0:2.8.3-3.rhel7 will be installed
--> Processing Dependency: postgresql-libs for package: python2-psycopg2-2.8.3-3.rhel7.x86_64
--> Processing Dependency: libpq.so.5()(64bit) for package: python2-psycopg2-2.8.3-3.rhel7.x86_64
--> Running transaction check
---> Package barman-cli.noarch 0:2.10-2.el7 will be installed
--> Processing Dependency: python-boto3 for package: barman-cli-2.10-2.el7.noarch
---> Package postgresql11-libs.x86_64 0:11.6-2PGDG.rhel7 will be installed
--> Finished Dependency Resolution
Error: Package: barman-cli-2.10-2.el7.noarch (2ndquadrant-dl-default-release-pg11)
           Requires: python-boto3
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

However, the package is available on CentOS:
https://centos.pkgs.org/7/centos-x86_64/python-boto3-1.4.6-5.el7.noarch.rpm.html

There may be some clever way to solve this problem, but nobody's been
able to tell me what it is in the past several weeks.

So for now, we just require barman-cli-2.9 on RH (all RH: it isn't worth
doing any extra work to exempt CentOS in this situation, when we need
only barman-wal-restore anyway).