Update install instructions for macOS platform (#173)
Instructions to setup homebrew discoteq project and install required pre-requisite software specify `sudo` which is no longer supported. It ends up with an error like the one below. Removed `sudo` from command-line instructions.

Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.