Add missing read/execute permissions for readonly harp dcs user
Readonly user for HARP proxy i.e. harp_dcs_user needs access to
following additional table and functions to seamlessly answer
harpctl queries:

 Table:
   bdr.local_node_summary
 Functions:
   bdr.monitor_group_raft
   bdr.get_raft_status
   bdr.peer_state_name

In the absence of read/execute permissions, `harpctl` commands would
throw following errors:

error: could not determine raft status: ERROR: permission denied for function monitor_group_raft (SQLSTATE 42501)

ERROR	bdr/bdr.go:728	could not get raft status: ERROR: permission denied for function get_raft_status (SQLSTATE 42501)

ERROR	bdr/bdr.go:754	could not get node_id: ERROR: permission denied for view local_node_summary (SQLSTATE 42501)

ERROR	bdr/bdr.go:754	could not get node_id: ERROR: permission denied for view local_node_summary (SQLSTATE 42501)

Closes TPA-67

Signed-off-by: Muhammad Haroon <muhammad.haroon@enterprisedb.com>