Revert "Don't use the pythonN-psycopg2 package at all"
This reverts commit 256fdbd, which we no longer need because disabling
PGDG repo entries for versions <> postgres_version solves the problem
we had with psycopg2 (and other) packages.

There are also problems with pip install'ing psycopg2-binary. Notably,
the pip that's shipped with Ubuntu is so old that it breaks:

    TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'