Remove "selinux" from python-requirements.txt
We want "import selinux" to fail with an ImportError so that
module_utils/basic (in Ansible) will decide that we don't HAVE_SELINUX.
If it's installed and the bindings are not available, then we get an
exception like this, and the workaround doesn't apply.

[vagrant@localhost ~]$ tpaexec selftest
tpaexec=/opt/2ndQuadrant/TPA/bin/tpaexec
TPA_DIR=/opt/2ndQuadrant/TPA
PYTHON=/opt/2ndQuadrant/TPA/tpa-venv/bin/python3 (v3.6.8, venv)
TPA_VENV=/opt/2ndQuadrant/TPA/tpa-venv
ANSIBLE=/opt/2ndQuadrant/TPA/tpa-venv/bin/ansible (v2.8.10)
ERROR! Unexpected Exception, this is probably a bug: Failed to detect selinux python bindings at ['/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']
the full traceback was:

Traceback (most recent call last):
  File "/opt/2ndQuadrant/TPA/tpa-venv/bin/ansible", line 90, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/opt/2ndQuadrant/TPA/tpa-venv/lib64/python3.6/site-packages/ansible/cli/__init__.py", line 25, in <module>
    from ansible.parsing.dataloader import DataLoader
  File "/opt/2ndQuadrant/TPA/tpa-venv/lib64/python3.6/site-packages/ansible/parsing/dataloader.py", line 17, in <module>
    from ansible.module_utils.basic import is_executable
  File "/opt/2ndQuadrant/TPA/tpa-venv/lib64/python3.6/site-packages/ansible/module_utils/basic.py", line 74, in <module>
    import selinux
  File "/opt/2ndQuadrant/TPA/tpa-venv/lib64/python3.6/site-packages/selinux/__init__.py", line 104, in <module>
    check_system_sitepackages()
  File "/opt/2ndQuadrant/TPA/tpa-venv/lib64/python3.6/site-packages/selinux/__init__.py", line 101, in check_system_sitepackages
    "Failed to detect selinux python bindings at %s" % system_sitepackages
Exception: Failed to detect selinux python bindings at ['/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']