Use ubuntu 20.04 for BlackDuck scans instead of `latest` which points to 22.04
Latest BlackDuck runner now points to ubuntu 22.04 which does not support
Python 3.6 since it reached EOL in December 2021. A run with Ubuntu
22.04 results in following error:

  Error: Version 3.6 with arch x64 not found.