Exit with an error if 'python3 -m venv' fails
Otherwise we issue two error messages:

+ mkdir -p /opt/EDB/TPA/tpa-venv
+ python3 -m venv /opt/EDB/TPA/tpa-venv
Error: Command '['/opt/EDB/TPA/tpa-venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
+ rm -rf /opt/EDB/TPA/tpa-venv
+ _activate_venv /opt/EDB/TPA/tpa-venv
…
ERROR: couldn't source /opt/EDB/TPA/tpa-venv/bin/activate (is /opt/EDB/TPA/tpa-venv a venv?)

We don't know why `python3 -m venv` failed here, but we already have an
error message, so we should just bail out.