Revert "Don't grant superuser permissions to repmgr"
This reverts commit 5d525dbd2c81c3596b63c96419c158dad42af6d2.

The earlier commit worked fine on M1, but running repmgr primary
register (with --superuser postgres) on a BDR node resulted in:

ERROR: unable to set "synchronous_commit": ERROR:  permission denied for schema pglogical

This is probably due to the inappropriate permissions checks from the
heap_openrv calls in pglogical, or it might be something else, but
whatever it is, we will have to deal with it later.