Run BlackDuck on ubuntu Noble
TPAexec now needs Python 3.12. The scanner uses just the system python.
Previous to this change, Python 3.10 was used and required other
dependencies:

Collecting urllib3==2.3.0
  Downloading urllib3-2.3.0-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.4/128.4 KB 45.3 MB/s eta 0:00:00
[...]
Collecting backports.tarfile
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
backports.tarfile from https://files.pythonhosted.org/packages/b9/fa/123043af240e49752f1c4bd24da5053b6bd00cad78c2be53c0d1e8b975bc/backports.tarfile-1.2.0-py3-none-any.whl#sha256=77e284d754527b01fb1e6fa8a1afe577858ebe4e9dad8919e34c862cb399bc34 (from jaraco-context==6.0.1->-r requirements.txt (line 235))
Error: Process completed with exit code 1.