Use python2/python3 explicitly in #! lines
This is because the RHEL8 build does this:

    + /usr/lib/rpm/redhat/brp-mangle-shebangs
    mangling shebang in /opt/2ndQuadrant/TPA/bin/tpaexec from /usr/bin/env bash to #!/usr/bin/bash
    mangling shebang in /opt/2ndQuadrant/TPA/platforms/lxd/inventory/lxd.py from /usr/bin/env python3 to #!/usr/libexec/platform-python
    …
    *** WARNING: ./opt/2ndQuadrant/TPA/architectures/Images/commands/build-images.sh is executable but has empty or no shebang, removing executable bit
    …
    *** ERROR: ambiguous python shebang in /opt/2ndQuadrant/TPA/roles/test/files/run_time_check.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
    error: Bad exit status from /var/tmp/rpm-tmp.76tHJ5 (%install)

We don't care about the warning: commands/*.sh weren't executable in the
source repository to begin with, nor do I know why it became executable,
so it becoming not executable again is fine with me. (It isn't meant to
be executed directly anyway.)